[package]
name = "bd"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "2.13.0", features = ["chrono-0_4"] }
chrono = "0.4.39"
dotenv = "0.15.0"
futures = "0.3.31"
mongodb = "3.2.1"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = "1.43.0"
